echo off
del unitest.lst
hpunimin \newfrank\ASSIGN    ASSIGN
\uni\as68000 -E +unitest.lst ASSIGN
spacemrk ASSIGN
copy unitest.lst + space
hpunimin \newfrank\AUTO_MID  AUTO_MID
\uni\as68000 -E +unitest.lst AUTO_MID
spacemrk AUTO_MID
copy unitest.lst + space
hpunimin \newfrank\BACKGROU  BACKGROU
\uni\as68000 -E +unitest.lst BACKGROU
spacemrk BACKGROU
copy unitest.lst + space
hpunimin \newfrank\BLOOZE    BLOOZE
\uni\as68000 -E +unitest.lst BLOOZE
spacemrk BLOOZE
copy unitest.lst + space
hpunimin \newfrank\DIAG440   DIAG440
\uni\as68000 -E +unitest.lst DIAG440
spacemrk DIAG440
copy unitest.lst + space
hpunimin \newfrank\EMULVECS  EMULVECS
\uni\as68000 -E +unitest.lst EMULVECS
spacemrk EMULVECS
copy unitest.lst + space
hpunimin \newfrank\FIELDS    FIELDS
\uni\as68000 -E +unitest.lst FIELDS
spacemrk FIELDS
copy unitest.lst + space
hpunimin \newfrank\FOOTPADS  FOOTPADS
\uni\as68000 -E +unitest.lst FOOTPADS
spacemrk FOOTPADS
copy unitest.lst + space
hpunimin \newfrank\FOOTSWBO  FOOTSWBO
\uni\as68000 -E +unitest.lst FOOTSWBO
spacemrk FOOTSWBO
copy unitest.lst + space
hpunimin \newfrank\GUIDO     GUIDO
\uni\as68000 -E +unitest.lst GUIDO
spacemrk GUIDO
copy unitest.lst + space
hpunimin \newfrank\KT_ALT_A  KT_ALT_A
\uni\as68000 -E +unitest.lst KT_ALT_A
spacemrk KT_ALT_A
copy unitest.lst + space
hpunimin \newfrank\LCD       LCD
\uni\as68000 -E +unitest.lst LCD
spacemrk LCD
copy unitest.lst + space
hpunimin \newfrank\LEVEL2    LEVEL2
\uni\as68000 -E +unitest.lst LEVEL2
spacemrk LEVEL2
copy unitest.lst + space
hpunimin \newfrank\LEVEL4    LEVEL4
\uni\as68000 -E +unitest.lst LEVEL4
spacemrk LEVEL4
copy unitest.lst + space
hpunimin \newfrank\LEVEL5    LEVEL5
\uni\as68000 -E +unitest.lst LEVEL5
spacemrk LEVEL5
copy unitest.lst + space
hpunimin \newfrank\LEVEL6    LEVEL6
\uni\as68000 -E +unitest.lst LEVEL6
spacemrk LEVEL6
copy unitest.lst + space
hpunimin \newfrank\MISCSUBS  MISCSUBS
\uni\as68000 -E +unitest.lst MISCSUBS
spacemrk MISCSUBS
copy unitest.lst + space
hpunimin \newfrank\NON_PRIO  NON_PRIO
\uni\as68000 -E +unitest.lst NON_PRIO
spacemrk NON_PRIO
copy unitest.lst + space
hpunimin \newfrank\PERF_MID  PERF_MID
\uni\as68000 -E +unitest.lst PERF_MID
spacemrk PERF_MID
copy unitest.lst + space
hpunimin \newfrank\PHASES    PHASES
\uni\as68000 -E +unitest.lst PHASES
spacemrk PHASES
copy unitest.lst + space
hpunimin \newfrank\PRIORITY  PRIORITY
\uni\as68000 -E +unitest.lst PRIORITY
spacemrk PRIORITY
copy unitest.lst + space
hpunimin \newfrank\PRO_CLIC  PRO_CLIC
\uni\as68000 -E +unitest.lst PRO_CLIC
spacemrk PRO_CLIC
copy unitest.lst + space
hpunimin \newfrank\PRO_MTC   PRO_MTC
\uni\as68000 -E +unitest.lst PRO_MTC
spacemrk PRO_MTC
copy unitest.lst + space
hpunimin \newfrank\PRO_PADS  PRO_PADS
\uni\as68000 -E +unitest.lst PRO_PADS
spacemrk PRO_PADS
copy unitest.lst + space
hpunimin \newfrank\PRO_TC    PRO_TC
\uni\as68000 -E +unitest.lst PRO_TC
spacemrk PRO_TC
copy unitest.lst + space
hpunimin \newfrank\RAM_440   RAM_440
\uni\as68000 -E +unitest.lst RAM_440
spacemrk RAM_440
copy unitest.lst + space
hpunimin \newfrank\REALTIME  REALTIME
\uni\as68000 -E +unitest.lst REALTIME
spacemrk REALTIME
copy unitest.lst + space
hpunimin \newfrank\RESET_44  RESET_44
\uni\as68000 -E +unitest.lst RESET_44
spacemrk RESET_44
copy unitest.lst + space
hpunimin \newfrank\ROMVECS   ROMVECS
\uni\as68000 -E +unitest.lst ROMVECS
spacemrk ROMVECS
copy unitest.lst + space
hpunimin \newfrank\SAMPLING  SAMPLING
\uni\as68000 -E +unitest.lst SAMPLING
spacemrk SAMPLING
copy unitest.lst + space
hpunimin \newfrank\SAMSUBS   SAMSUBS
\uni\as68000 -E +unitest.lst SAMSUBS
spacemrk SAMSUBS
copy unitest.lst + space
hpunimin \newfrank\SEQCHASE  SEQCHASE
\uni\as68000 -E +unitest.lst SEQCHASE
spacemrk SEQCHASE
copy unitest.lst + space
hpunimin \newfrank\SEQFUNS1  SEQFUNS1
\uni\as68000 -E +unitest.lst SEQFUNS1
spacemrk SEQFUNS1
copy unitest.lst + space
hpunimin \newfrank\SEQFUNS2  SEQFUNS2
\uni\as68000 -E +unitest.lst SEQFUNS2
spacemrk SEQFUNS2
copy unitest.lst + space
hpunimin \newfrank\SEQFUNS3  SEQFUNS3
\uni\as68000 -E +unitest.lst SEQFUNS3
spacemrk SEQFUNS3
copy unitest.lst + space
hpunimin \newfrank\SEQFUNS4  SEQFUNS4
\uni\as68000 -E +unitest.lst SEQFUNS4
spacemrk SEQFUNS4
copy unitest.lst + space
hpunimin \newfrank\SEQSUBS   SEQSUBS
\uni\as68000 -E +unitest.lst SEQSUBS
spacemrk SEQSUBS
copy unitest.lst + space
hpunimin \newfrank\SEQ_MIDI  SEQ_MIDI
\uni\as68000 -E +unitest.lst SEQ_MIDI
spacemrk SEQ_MIDI
copy unitest.lst + space
hpunimin \newfrank\SNDFUNS1  SNDFUNS1
\uni\as68000 -E +unitest.lst SNDFUNS1
spacemrk SNDFUNS1
copy unitest.lst + space
hpunimin \newfrank\SNDFUNS2  SNDFUNS2
\uni\as68000 -E +unitest.lst SNDFUNS2
spacemrk SNDFUNS2
copy unitest.lst + space
hpunimin \newfrank\SNDFUNS3  SNDFUNS3
\uni\as68000 -E +unitest.lst SNDFUNS3
spacemrk SNDFUNS3
copy unitest.lst + space
hpunimin \newfrank\SOFTDIAG  SOFTDIAG
\uni\as68000 -E +unitest.lst SOFTDIAG
spacemrk SOFTDIAG
copy unitest.lst + space
hpunimin \newfrank\SONGFUNS  SONGFUNS
\uni\as68000 -E +unitest.lst SONGFUNS
spacemrk SONGFUNS
copy unitest.lst + space
hpunimin \newfrank\SWITCHBO  SWITCHBO
\uni\as68000 -E +unitest.lst SWITCHBO
spacemrk SWITCHBO
copy unitest.lst + space
hpunimin \newfrank\SYSFUNS1  SYSFUNS1
\uni\as68000 -E +unitest.lst SYSFUNS1
spacemrk SYSFUNS1
copy unitest.lst + space
hpunimin \newfrank\SYSFUNS2  SYSFUNS2
\uni\as68000 -E +unitest.lst SYSFUNS2
spacemrk SYSFUNS2
copy unitest.lst + space
hpunimin \newfrank\SYSFUNS3  SYSFUNS3
\uni\as68000 -E +unitest.lst SYSFUNS3
spacemrk SYSFUNS3
copy unitest.lst + space
hpunimin \newfrank\SYSFUNS4  SYSFUNS4
\uni\as68000 -E +unitest.lst SYSFUNS4
spacemrk SYSFUNS4
copy unitest.lst + space
hpunimin \newfrank\SYS_EX    SYS_EX
\uni\as68000 -E +unitest.lst SYS_EX
spacemrk SYS_EX
copy unitest.lst + space
hpunimin \newfrank\TABLES    TABLES
\uni\as68000 -E +unitest.lst TABLES
spacemrk TABLES
copy unitest.lst + space
hpunimin \newfrank\TEMPO     TEMPO
\uni\as68000 -E +unitest.lst TEMPO
spacemrk TEMPO
copy unitest.lst + space
hpunimin \newfrank\TRANSPOR  TRANSPOR
\uni\as68000 -E +unitest.lst TRANSPOR
spacemrk TRANSPOR
copy unitest.lst + space
hpunimin \newfrank\TRIGRBOY  TRIGRBOY
\uni\as68000 -E +unitest.lst TRIGRBOY
spacemrk TRIGRBOY
copy unitest.lst + space
hpunimin \newfrank\TUNE_TAB  TUNE_TAB
\uni\as68000 -E +unitest.lst TUNE_TAB
spacemrk TUNE_TAB
copy unitest.lst + space
hpunimin \newfrank\VINITMAI  VINITMAI
\uni\as68000 -E +unitest.lst VINITMAI
spacemrk VINITMAI
copy unitest.lst + space
hpunimin \newfrank\VINITSUB  VINITSUB
\uni\as68000 -E +unitest.lst VINITSUB
spacemrk VINITSUB
copy unitest.lst + space
hpunimin \newfrank\DISKCMD1  DISKCMD1
\uni\as68000 -E +unitest.lst DISKCMD1
spacemrk DISKCMD1
copy unitest.lst + space
hpunimin \newfrank\DISKCMD2  DISKCMD2
\uni\as68000 -E +unitest.lst DISKCMD2
spacemrk DISKCMD2
copy unitest.lst + space
hpunimin \newfrank\DISKLOW1  DISKLOW1
\uni\as68000 -E +unitest.lst DISKLOW1
spacemrk DISKLOW1
copy unitest.lst + space
hpunimin \newfrank\DISKLOW2  DISKLOW2
\uni\as68000 -E +unitest.lst DISKLOW2
spacemrk DISKLOW2
copy unitest.lst + space
hpunimin \newfrank\DISKLOW3  DISKLOW3
\uni\as68000 -E +unitest.lst DISKLOW3
spacemrk DISKLOW3
copy unitest.lst + space
hpunimin \newfrank\DISKMAIN  DISKMAIN
\uni\as68000 -E +unitest.lst DISKMAIN
spacemrk DISKMAIN
copy unitest.lst + space
hpunimin \newfrank\GNRCSCSI  GNRCSCSI
\uni\as68000 -E +unitest.lst GNRCSCSI
spacemrk GNRCSCSI
copy unitest.lst + space
hpunimin \newfrank\SCSICMDS  SCSICMDS
\uni\as68000 -E +unitest.lst SCSICMDS
spacemrk SCSICMDS
copy unitest.lst + space
